# R8 and R52 text dataset
nltk only contains the whole corpus ([docs](https://www.nltk.org/book/ch02.html)) so I built the subsets by hand by following the explanation [here](https://ana.cachopo.org/datasets-for-single-label-text-categorization).

The number of docs in the datasets **do not match** the numbers in the Text GCN paper as I got slightly more docs! This might be because the nltk version contains some "fixed" docs which incorrectly had multiple or no classes (read explanation). I manually checked some classes with the different numbers and they seemed fine (so all docs had a single class) The classes match at least!

Also note that stop-words are already removed (unlike in Text GCN).

Since our goal is not to reproduce the paper, I just accepted these things

Making a graph dataset out of this is TODO

In [1]:
from torch.utils.data import DataLoader
from transformers import RobertaTokenizer
from datasets.reuters_text import R8, R52

[nltk_data] Downloading package reuters to /home/mat/nltk_data...
[nltk_data]   Package reuters is already up-to-date!


In [2]:
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

In [3]:
r52_train, r52_test, r52_val = R52.splits(tokenizer, val_size=0.1)
r8_train,  r8_test, r8_val  = R8.splits(tokenizer, val_size=0.1)

In [4]:
print('R8')
print('train size:', len(r8_train), ' instead of 5485')
print('test size:', len(r8_test), ' instead of 2189')
print('val size:', len(r8_val))

print('R52')
print('train size:', len(r52_train), ' instead of 6532')
print('test size:', len(r52_test), ' instead of 2568')
print('val size:', len(r52_val))

R8
train size: 4951  instead of 5485
test size: 2190  instead of 2189
val size: 550
R52
train size: 5904  instead of 6532
test size: 2570  instead of 2568
val size: 656


In [5]:
r52_train_dataloader = DataLoader(r52_train, batch_size=2, shuffle=True)

for data in r52_train_dataloader:
    input_ids = data["input_ids"]
    attention_mask = data["attention_mask"]
    labels = data["labels"]
    print(input_ids)
    print(attention_mask)
    print(labels)
    break

tensor([[    0,   725, 11969,  ...,     1,     1,     1],
        [    0, 26107,   359,  ...,     1,     1,     1]])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])
tensor([12, 12])
